excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - force_cast
  - conditional_binding_cascade
variable_name:
    min_length: 2

line_length: 180
